---
title: "External Resources"
format: 
  html:
    page-layout: full
    link-external-newwindow: true
    toc: true
    highlight-style: ayu
---

+-----------+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
| Lesson \# | Lesson/Theme Name                 | Resources                                                                                                                                                                                        |       |
+===========+===================================+==================================================================================================================================================================================================+=======+
|           | Health and Retirement Study (HRS) | - [Check out the codebook I made for us!](../../resources/HRS_codebook.qmd)                                                                                                                      |       |
+-----------+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|           | Objects                           | - There is an additional textbook: [Hands-On Programming with R by Garrett Grolemund](https://www.rstudio.com/resources/books/hands-on-programming-with-r/)                                      |       |
|           |                                   |   - [Here is the chapter on objects](https://rstudio-education.github.io/hopr/r-objects.html)                                                                                                    |       |
|           |                                   | - [Page on tibble package](https://tibble.tidyverse.org/)                                                                                                                                        |       |
+-----------+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|           | Packages                          | - Danielle Navarro’s YouTube video on ***Installing and loading R packages***: <https://www.youtube.com/watch?v=kpHZVyDvEhQ>                                                                     |       |
|           |                                   |   - If you want to get more information on packages                                                                                                                                              |       |
|           |                                   | - [Comprehensive R Archive Network (CRAN)](https://cran.r-project.org/) = package mothership                                                                                                     |       |
|           |                                   | - There is an additional textbook: [Hands-On Programming with R by Garrett Grolemund](https://www.rstudio.com/resources/books/hands-on-programming-with-r/)                                      |       |
|           |                                   |   - [Here is the chapter on packages](https://rstudio-education.github.io/hopr/packages.html#getting-help-with-help-pages)                                                                       |       |
+-----------+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|           | Quarto documents                  | - To learn more about working with Quarto, check out our BERD workshop: [*Creating Professional Presentations and Websites using R/Quarto*](https://ohsu-octri-berd.github.io/Quarto_BERD_2025/) |       |
+-----------+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|           | Data transformations              | - `dplyr` [cheat sheet](https://rstudio.github.io/cheatsheets/html/data-transformation.html)                                                                                                     |       |
+-----------+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|           | Data visualization (`ggplot2`)    | - `ggplot2` package website: <https://ggplot2.tidyverse.org/articles/ggplot2.html>                                                                                                               |       |
|           |                                   | - Online textbook for `ggplot2`: <https://ggplot2-book.org/>                                                                                                                                     |       |
|           |                                   | - Another online resource for data visualization with `ggplot2`: <https://socviz.co/index.html#preface>                                                                                          |       |
|           |                                   | - [Advanced Data Viz Class at Duke](https://vizdata.org/)                                                                                                                                        |       |
+-----------+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|           |                                   |                                                                                                                                                                                                  |       |
+-----------+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|           |                                   |                                                                                                                                                                                                  |       |
+-----------+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|           |                                   |                                                                                                                                                                                                  |       |
+-----------+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|           |                                   |                                                                                                                                                                                                  |       |
+-----------+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|           |                                   |                                                                                                                                                                                                  |       |
+-----------+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|           |                                   |                                                                                                                                                                                                  |       |
+-----------+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|           |                                   |                                                                                                                                                                                                  |       |
+-----------+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|           |                                   |                                                                                                                                                                                                  |       |
+-----------+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|           |                                   |                                                                                                                                                                                                  |       |
+-----------+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|           |                                   |                                                                                                                                                                                                  |       |
+-----------+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|           |                                   |                                                                                                                                                                                                  |       |
+-----------+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|           |                                   |                                                                                                                                                                                                  |       |
+-----------+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|           |                                   |                                                                                                                                                                                                  |       |
+-----------+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|           |                                   |                                                                                                                                                                                                  |       |
+-----------+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|           |                                   |                                                                                                                                                                                                  |       |
+-----------+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|           |                                   |                                                                                                                                                                                                  |       |
+-----------+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|           |                                   |                                                                                                                                                                                                  |       |
+-----------+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|           |                                   |                                                                                                                                                                                                  |       |
+-----------+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|           |                                   |                                                                                                                                                                                                  |       |
+-----------+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|           |                                   |                                                                                                                                                                                                  |       |
+-----------+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|           |                                   |                                                                                                                                                                                                  |       |
+-----------+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
|           |                                   |                                                                                                                                                                                                  |       |
+-----------+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------+
