---
title: "Schedule"
format: 
  html:
    page-layout: full
    link-external-newwindow: true
    toc: true
    highlight-style: ayu
---

```{css, echo=FALSE}
.title{
  font-size: 30px;
  color: #3070BF;
  background-color: #fff;
  padding: 0px;
}

.sched table tbody tr:has(.rbasics) td:nth-child(4){
  background-color: #fcf2f7 !important;
  color: #EF85B3; 
}

.sched table tbody tr:has(.info) td:nth-child(4){
  background-color: #F8F9FA !important;
  color: #6C757D; 
}

.sched table tbody tr:has(.randr) td:nth-child(4){
  background-color: #FCF3E2 !important;
  color: #F39C12; 
}

.sched table tbody tr:has(.bestpract) td:nth-child(4){
  background-color: #DAECFE !important;
  color: #5BAFF8; 
}

.sched table tbody tr:has(.trans) td:nth-child(4){
  background-color: #D0DDF1 !important;
  color: #3070BF; 
}

.sched table tbody tr:has(.summ) td:nth-child(4){
  background-color: #D9E8E9 !important;
  color: #459B99; 
}

.sched table tbody tr:has(.viz) td:nth-child(4){
  background-color: #FFE6E6 !important;
  color: #C83532; 
}

.sched table tbody tr:has(.pract-row) td, 
.sched table tbody tr:has(.proj-row) td,
.sched table tbody tr:has(.lab-row) td{
  background-color: #F8EAF0 !important;
  color: #BF396F; 
}

.sched table tbody tr:has(.week-row) td{
  background-color: #3070BF !important; /* A light red; use 'red' for bright red */
  color: #fff; 
  font-size: 0px;     /* Collapses the text height */
  height: 5px;
}

.sched table th:nth-of-type(1) {
  width: 5% !important;
}
.sched table th:nth-of-type(2) {
  width: 5% !important;
}
.sched table th:nth-of-type(3) {
  width: 5% !important;
}
.sched table th:nth-of-type(4) {
  width: 18% !important;
}
.sched table th:nth-of-type(5) {
  width: 30% !important;
}
.sched table th:nth-of-type(6) {
  width: 5% !important;
}
.sched table th:nth-of-type(7) {
  width: 5% !important;
}
.sched table th:nth-of-type(8) {
  width: 10% !important;
}
.sched table th:nth-of-type(9) {
  width: 10% !important;
}
```

```{r setup, include=FALSE}
library(here)
source(here("class_dates.R"))
```

::: sched
| Week | Date | Les-son | Theme | Topic | Lesson video | Slides | [TB 1](https://r4ds.hadley.nz/) | [TB 2](https://epirhandbook.com/en/) |
|:-------|:-------|:-------|--------|:-------|:------:|:------:|:------:|:------:|
| 1 | `{r} w1d1 %>% format("%m/%d")` | 1 | [Course info]{.info} | Welcome | [[{{< iconify mdi video size=34px >}}](https://www.loom.com/share/30380318cd394eeca67f2008319beda5)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/01_Welcome/Welcome.qmd)]{style="color:#f8f5f0;"} | [Intro](https://r4ds.hadley.nz/intro.html) |  |
|  |  | 2 | [Course info]{.info} | Course logistics | [[{{< iconify mdi video size=34px >}}](https://www.loom.com/share/aa9a5dfec11c47d79eb88fe394bb2282)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/02_Course_log/Course_log.qmd)]{style="color:#f8f5f0;"} |  |  |
|  |  | 3 | [R Basics]{.rbasics} | Download + Intro to R & Rstudio | [[{{< iconify mdi video size=34px >}}](https://www.loom.com/share/77f8aea2a5bf4b26acc886a28de33569)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/03_Download_R/Download_R.qmd)]{style="color:#f8f5f0;"} |  | [3.4-3.5](https://epirhandbook.com/en/new_pages/basics.html#installation) |
|  |  | 4 | [R Basics]{.rbasics} | R scripts | [[{{< iconify mdi video size=34px >}}](https://www.loom.com/share/dae3a73b80f540189f60f1ed547917fc)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/04_Scripts/Scripts.qmd)]{style="color:#f8f5f0;"} | [6.1](https://r4ds.hadley.nz/workflow-scripts.html#scripts) | [3.8](https://epirhandbook.com/en/new_pages/basics.html#scripts) |
|  |  | 5 | [R Basics]{.rbasics} | Basics | [[{{< iconify mdi video size=34px >}}](https://www.loom.com/share/520012d15ef442109896878ba8c5683c)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/05_Basics_operators/Basics_operators.qmd)]{style="color:#f8f5f0;"} | [2.1](https://r4ds.hadley.nz/workflow-basics.html) | [8.2](https://epirhandbook.com/en/new_pages/basics.html#operators) |
|  |  | 6 | [Best Practices in R]{.bestpract} | Comments | [[{{< iconify mdi video size=34px >}}](https://www.loom.com/share/79cbe592ce374632b497d4d50e732cdb)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/06_Comments/Comments.qmd)]{style="color:#f8f5f0;"} | [2.2](https://r4ds.hadley.nz/workflow-basics.html#comments) |  |
|  | `{r} pract1 %>% format("%m/%d")` |  |  | [Practice 1 due]{.pract-row} |  |  |  |  |
| [ ]{.week-row} |  |  |  |  |  |  |  |  |
| 2 | `{r} w2d1 %>% format("%m/%d")` | 7 | [Rigor & Reproducibility]{.randr} | Folder and file Organization | [[{{< iconify mdi video size=34px >}}](https://www.loom.com/share/06734d1ad7204da0a8587f04ae3923ed)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/07_Organization/Organization.qmd)]{style="color:#f8f5f0;"} |  |  |
|  |  | 8 | [Rigor & Reproducibility]{.randr} | Quarto and `.qmd`'s | [[{{< iconify mdi video size=34px >}}](https://www.loom.com/share/74a90b5fe7be4cbeaa38009363e33ad6)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/08_Quarto_docs/Quarto_docs.qmd)]{style="color:#f8f5f0;"} | [28](https://r4ds.hadley.nz/quarto.html) |  |
|  |  | 9 | [R Basics]{.rbasics} | Packages | [[{{< iconify mdi video size=34px >}}](https://www.loom.com/share/32ed9bec751b48e9aa53981d72d0c0f2)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/09_Packages/Packages.qmd)]{style="color:#f8f5f0;"} |  | [3.7](https://epirhandbook.com/en/new_pages/basics.html#packages) |
|  |  | 10 | [Rigor & Reproducibility]{.randr} | R projects and working directories | [[{{< iconify mdi video size=34px >}}](https://www.loom.com/share/ad8129f76cdb46509ffd5f8bf4050b94)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/10_Rproj_wds/Rproj_wds.qmd)]{style="color:#f8f5f0;"} | [6.2.3-6.2.4](https://r4ds.hadley.nz/workflow-scripts.html#rstudio-projects) | [6](https://epirhandbook.com/en/new_pages/r_projects.html) |
|  | `{r} pract2 %>% format("%m/%d")` |  |  | [Practice 2 due]{.pract-row} |  |  |  |  |
| [ ]{.week-row} |  |  |  | Nicky on vacation this week |  |  |  |  |
| 3 | `{r} w3d1 %>% format("%m/%d")` | 11 | [Course info]{.info} | Introduction to HRS dataset | [[{{< iconify mdi video size=34px >}}](https://www.loom.com/share/c6b9a396d1df4dd8bd14cd30b7f71659)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/11_Intro_to_HRS/Intro_to_HRS.qmd)]{style="color:#f8f5f0;"} |  |  |
|  |  | 12 | [R Basics]{.rbasics} | Functions | [[{{< iconify mdi video size=34px >}}](https://www.loom.com/share/fbccebe3180c44a38b46108138bf8bb8)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/12_Functions/Functions.qmd)]{style="color:#f8f5f0;"} | [2.4](https://r4ds.hadley.nz/workflow-basics.html#calling-functions) | [3.6](https://epirhandbook.com/en/new_pages/basics.html#functions) |
|  |  | 13 | [R Basics]{.rbasics} | Objects | [[{{< iconify mdi video size=34px >}}](https://www.loom.com/share/910d90d7a8d9444f8d6f9b256b84e334)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/13_Objects/Objects.qmd)]{style="color:#f8f5f0;"} |  | [3.10](https://epirhandbook.com/en/new_pages/basics.html#objects) |
|  |  | 14 | [Best Practices in R]{.bestpract} | Common Errors | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/14_Common_errors/Common_errors.qmd)]{style="color:#f8f5f0;"} |  | [47.2](https://epirhandbook.com/en/new_pages/errors.html#common-errors) |
|  |  | 15 | [Best Practices in R]{.bestpract} | Getting help | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/15_Getting_help/Getting_help.qmd)]{style="color:#f8f5f0;"} | [8](https://r4ds.hadley.nz/workflow-help.html) |  |
|  | `{r} pract3 %>% format("%m/%d")` |  |  | [Practice 3 Due]{.pract-row} |  |  |  |  |
| [ ]{.week-row} |  |  |  | Nicky out of town, but can answer emails |  |  |  |  |
| 4 | `{r} w4d1 %>% format("%m/%d")` | 16 | [R Basics]{.rbasics} | Piping | [[{{< iconify mdi video size=34px >}}](https://www.loom.com/share/c93b11b205f7404991e2d16fc7cfc829)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](./lessons/16_Piping/Piping.qmd)]{style="color:#f8f5f0;"} | [3.4](https://r4ds.hadley.nz/data-transform.html#sec-the-pipe), [4.3](https://r4ds.hadley.nz/workflow-style.html#sec-pipes) | [8.1](https://epirhandbook.com/en/new_pages/basics.html#piping) |
|  |  | 17 | [R Basics]{.rbasics} | Key operators and functions | [[{{< iconify mdi video size=34px >}}](https://www.loom.com/share/32b44e841ec64091ac0f8b3e66fa47fd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](./lessons/17_Key_operators/Key_operators.qmd)]{style="color:#f8f5f0;"} | [12.3](https://r4ds.hadley.nz/logicals.html#boolean-algebra) | [8.2](https://epirhandbook.com/en/new_pages/basics.html#operators) |
|  |  | 18 | [R Basics]{.rbasics} | Import and Export | [[{{< iconify mdi video size=34px >}}](https://www.loom.com/share/cad115be79604eacbe5c267c79598e9a)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](./lessons/19_Import_Export/Import_Export.qmd)]{style="color:#f8f5f0;"} | [7](https://r4ds.hadley.nz/data-import.html) | [7](https://epirhandbook.com/en/new_pages/importing.html) |
|  |  | 19 | [R Basics]{.rbasics} | Tidy data | [[{{< iconify mdi video size=34px >}}](https://www.loom.com/share/978a81ca06f04fec8d092ca78e60b2ec)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](./lessons/18_Tidy_data/Tidy_data.qmd)]{style="color:#f8f5f0;"} | [5.2](https://r4ds.hadley.nz/data-tidy.html#sec-tidy-data) | [4.1](https://epirhandbook.com/en/new_pages/transition_to_R.html#tidy-data) |
|  | `{r} pract4 %>% format("%m/%d")` |  |  | [Practice 4 due]{.pract-row} |  |  |  |  |
|  | `{r} lab1 %>% format("%m/%d")` |  |  | [Lab 1 due]{.lab-row} |  |  |  |  |
| [ ]{.week-row} |  |  |  |  |  |  |  |  |
| 5 | `{r} w5d1 %>% format("%m/%d")` | 21 | [Data transformation]{.trans} | Intro to data transformations and summarizations | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/17_Intro_data_trans_summ/17_Intro_data_trans_summ.qmd)]{style="color:#f8f5f0;"} | [3.1](https://r4ds.hadley.nz/data-transform.html#introduction) |  |
|  |  | 22 | [Data transformation]{.trans} | Data transformation: rows | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/18_Data_transformation_rows/18_Data_transformation_rows.qmd)]{style="color:#f8f5f0;"} | [3.2](https://r4ds.hadley.nz/data-transform.html#rows) | [13.7-13.8](https://epirhandbook.com/en/new_pages/grouping.html#arranging-grouped-data) |
|  |  | 23 | [Data transformation]{.trans} | Data transformation: columns | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/19_Data_transformation_columns/19_Data_transformation_columns.qmd)]{style="color:#f8f5f0;"} | [3.3](https://r4ds.hadley.nz/data-transform.html#columns) |  |
|  |  | 24 | [Data transformation]{.trans} | Data transformations: advanced | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"} | [12.2](https://r4ds.hadley.nz/logicals.html#comparisons), [16](https://r4ds.hadley.nz/factors.html) |  |
|  |  |  |  | Common errors for data transformations |  |  |  |  |
|  | `{r} pract5 %>% format("%m/%d")` |  |  | [Practice 5 due]{.pract-row} |  |  |  |  |
| [ ]{.week-row} |  |  |  |  |  |  |  |  |
| 6 | `{r} w6d1 %>% format("%m/%d")` | 25 | [Data summarization]{.summ} | Data summarization: quantitative data | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"} | [3.5](https://r4ds.hadley.nz/data-transform.html#groups) |  |
|  |  | 26 | [Data summarization]{.summ} | Data summarization: categorical data | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"} |  |  |
|  |  | 27 | [Data summarization]{.summ} | Descriptive tables | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"} |  | [17](https://epirhandbook.com/en/new_pages/tables_descriptive.html) |
|  |  |  |  | Common errors for data summarizations |  |  |  |  |
|  | `{r} pract6 %>% format("%m/%d")` |  |  | [Practice 6 due]{.pract-row} |  |  |  |  |
|  | `{r} lab2 %>% format("%m/%d")` |  |  | [Lab 2 due]{.lab-row} |  |  |  |  |
| [ ]{.week-row} |  |  |  |  |  |  |  |  |
| 7 | `{r} w7d1 %>% format("%m/%d")` | 28 | [Data transformation]{.trans} | Lengthening data | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"} | [5.3](https://r4ds.hadley.nz/data-tidy.html#sec-pivoting) |  |
|  |  | 29 | [Data transformation]{.trans} | Widening data | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"} | [5.4](https://r4ds.hadley.nz/data-tidy.html#widening-data) |  |
|  |  |  | [Rigor & Reproducibility]{.randr} | More on quarto |  |  |  |  |
|  | `{r} pract7 %>% format("%m/%d")` |  |  | [Practice 7 due]{.pract-row} |  |  |  |  |
|  | `{r} lab3 %>% format("%m/%d")` |  |  | [Lab 3 due]{.lab-row} |  |  |  |  |
| [ ]{.week-row} |  |  |  |  |  |  |  |  |
| 8 | `{r} w8d1 %>% format("%m/%d")` | 30 | [Data visualization]{.viz} | Data visualization: Intro to ggplot | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/26_Data_viz_Intro_to_ggplot/26_Data_viz_Intro_to_ggplot.qmd)]{style="color:#f8f5f0;"} | [1.1-1.3](https://r4ds.hadley.nz/data-visualize.html#introduction) | [30.2-30.5](https://epirhandbook.com/en/new_pages/ggplot_basics.html#basics-of-ggplot) |
|  |  | 31 | [Data visualization]{.viz} | Data visualization: Basic plotting | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/30_Data_viz_Basic_plotting/30_Data_viz_Basic_plotting.qmd)]{style="color:#f8f5f0;"} | [9.2-9.3](https://r4ds.hadley.nz/layers.html#aesthetic-mappings) | [30.4-30.5](https://epirhandbook.com/en/new_pages/ggplot_basics.html#geoms) |
|  |  | 32 | [Data visualization]{.viz} | Data visualization: Design choices | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"} | [1.5](https://r4ds.hadley.nz/data-visualize.html#visualizing-relationships) |  |
|  |  |  |  | Common errors for data visualization |  |  |  |  |
|  | `{r} pract8 %>% format("%m/%d")` |  |  | [Practice 8 due]{.pract-row} |  |  |  |  |
| [ ]{.week-row} |  |  |  |  |  |  |  |  |
| 9 | `{r} w9d1 %>% format("%m/%d")` | 33 |  | Missing data: summarization and visualization | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"} |  |  |
|  |  | 34 |  | Missing data: transformations | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"} |  |  |
|  | `{r} pract9 %>% format("%m/%d")` |  |  | [Practice 9 due]{.pract-row} |  |  |  |  |
|  | `{r} lab4 %>% format("%m/%d")` |  |  | [Lab 4 due]{.lab-row} |  |  |  |  |
| [ ]{.week-row} |  |  |  |  |  |  |  |  |
| 10 | `{r} w10d1 %>% format("%m/%d")` |  | [Course info]{.info} | Project help |  |  |  |  |
| [ ]{.week-row} |  |  |  |  |  |  |  |  |
| 11 | `{r} w11d1 %>% format("%m/%d")` |  |  | [Final Project due]{.proj-row} |  |  |  |  |
:::
