---
title: "Homework 0"
subtitle: "PUBH 523/623"
description: "Due: `r library(here); source(here('class_dates.R')); hw0 %>% format('%m/%d')`"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
    toc: true
  pdf: default 
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: "setup"
#| include: false
knitr::opts_chunk$set(echo = TRUE)

library(here)
source(here("class_dates.R"))
```

::: {.callout-note appearance="minimal"}
**This homework does not need to be turned in on Brightspace.**
:::

### Purpose

This homework is meant to introduce yourself to me and your peers and make sure we can access RStudio on our computers.

### Grading

Grading will be done as a check/no check for turning in your work.

## Questions

### Question 1

Join our [Slack workspace](https://join.slack.com/t/pubh523623/shared_invite/zt-40eg9bxpw-IW_2bAyq6SiXdn1q_tl2Yg).

### Question 2

Edit your Slack profile with the following changes:

- Please upload a picture of yourself. **Make sure your face is visible in this picture.** It will help me identify you. [Here is a video with instructions.](https://www.youtube.com/watch?v=TeXWkNz81jU)
- Provide a pronunciation of your name. [Here is a video with instructions.](https://www.youtube.com/watch?v=eJJYArMr2-A)
- If you are comfortable sharing your pronouns, please edit your name to include them at the end. For example, my profile says "Nicky Wakim (she/her)"

### Question 3

Please complete the [following when2meet poll](https://www.when2meet.com/?37037592-Wdcqx) so that we can schedule office hours. Please use a unique identifier (does not have to be your name), so that I can make sure each student can attend at least one office hour.

### Question 4

In Slack, send a direct message to me with a screenshot of your Rstudio window open. This is to make sure you have access to Rstudio and can use it for our class. **If you have any issues with Rstudio, please let me know ASAP and we can troubleshoot together.**

### Question 5 (OPTIONAL)

Completion of this question is only necessary if you have accommodations. If you have any learning accommodations, please email me about your needs. I should receive a direct email from the Office of Student Access, but it is important that we discuss how accommodations will translate to our class. If you plan to seek accommodations, but do not have the formal document yet, please let me know!

I highly suggest that you make an appointment with a learning specialist through [Student Academic Support Services](https://Brightspace.ohsu.edu/portal/site/Student_Support)! If you often need more time on a test, struggle to focus in class, or noticed a difference between your learning style and typical styles offered in school, **talk to academic support services and see if you qualify for accommodations!** Most professors should be working towards an inclusive classroom, but this is the best way to insure you get the learning environment you need!

