---
title: "Introduction to HRS dataset"
author: "Nicky Wakim"
title-slide-attributes:
    data-background-color: "#3070BF"
format: 
  revealjs:
    theme: "../simple_NW.scss"
    chalkboard: true
    slide-number: true
    show-slide-number: all
    width: 1955
    height: 1100
    footer: "Introduction to HRS dataset"
    html-math-method: mathjax
    highlight-style: ayu
code-annotations: hover
execute:
  echo: true
  freeze: auto
---

```{r}
#| label: "setup" 
#| include: false
#| message: false
#| warning: false

pacman::p_load(
  tidyverse, 
  lubridate,
  janitor,
  here
)
```

## The Health and Retirement Study (HRS)

[From HRS website:](https://hrs.isr.umich.edu/about)

> The University of Michigan Health and Retirement Study (HRS) is a longitudinal panel study that surveys a representative sample of approximately 20,000 people in America, supported by the National Institute on Aging (NIA U01AG009740) and the Social Security Administration.

 

- HRS measures many **aspects of aging**, including health, retirement, and economic status

## We are using *synthetic* data

- We will be working with a **synthetic** dataset from HRS
  - We will be using this dataset in our lessons

 

- HRS is a protected dataset, so I cannot publish the real data

 

- My synthetic dataset has the same structure and variables as the real HRS data
  - Initial correlations of the data are not preserved in this dataset!!

## A little bit more info on our dataset

- We have measurements on **2,728 synthetic individuals from the HRS dataset**

 

- Measurements include:
  - Household information
  - Demographics
  - Health behaviors
  - Phyiscal health information
  - Mental health information
  - Economic information

## Resources

- [Check out the codebook I made for us!](../../resources/HRS_codebook.qmd)

## Note on AI usage

- I used some AI to help me clean the data, rename variables, and label variables
- I also asked AI to help me make the codebook
