---
title: "HRS Codebook"
format: 
  html:
    page-layout: full
    link-external-newwindow: true
    toc: true
    highlight-style: ayu
---

+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| Position | Name            | Label                                           | Type      | Unit / Levels                         | Original HRS Name |
+:========:+:================+:================================================+:==========+:======================================+:==================+
| 1        | `hhid`          | Household ID                                    | character |                                       | `HHID`            |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 2        | `pn`            | Person Number                                   | character |                                       | `PN`              |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 3        | `id`            | Household identifier + person number identifier | character |                                       | `HHIDPN`          |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 4        | `BIRTHYR`       | Respondent Birth Year                           | numeric   | years                                 | `RABYEAR`         |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 5        | `BIRTHMO`       | Respondent Birth Month                          | factor    | - 1-12 for each month Jan-Dec         | `RABMONTH`        |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - Unknown (if 0)                      |                   |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 6        | `BIRTHDATE`     | Respondent Birth Date                           | numeric   |                                       | `RABDATE`         |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 7        | `proxy`         | Proxy Interview Status                          | factor    | - Self                                | `R16PROXY`        |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - Proxy interview                     |                   |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 8        | `coupled`       | Couple Household Status                         | factor    | - Single                              | `H16CPL`          |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - Coupled/partnered                   |                   |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 9        | `sex`           | Sex                                             | factor    | - Male                                | `RAGENDER`        |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - Female                              |                   |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 10       | `age_mo`        | Age at Interview (Months)                       | numeric   | months                                | `R16AGEM_B`       |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 11       | `age_yr`        | Age at Interview (Years)                        | numeric   | years                                 | `R16AGEY_B`       |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 12       | `ed`            | Years of Education                              | numeric   | years                                 | `RAEDYRS`         |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 13       | `degree`        | Highest Degree Earned                           | factor    | - None                                | `RAEDEGRM`        |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - GED                                 |                   |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - High school diploma                 |                   |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - Associate's degree                  |                   |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - Bachelor's degree                   |                   |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - Master's degree                     |                   |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - Professional degree (Ph.D./M.D./JD) |                   |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 14       | `race_original` | Race/Ethnicity                                  | factor    | - White/Caucasian                     | `RARACEM`         |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - Black/African American              |                   |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - Other                               |                   |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 15       | `smoke_ever`    | Ever Smoked                                     | factor    | - No                                  | `R16SMOKEV`       |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - Yes                                 |                   |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 16       | `smoke_now`     | Current Smoker                                  | factor    | - No                                  | `R16SMOKEN`       |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - Yes                                 |                   |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 17       | `drink`         | Current Drinker                                 | factor    | - No                                  | `R16DRINK`        |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - Yes                                 |                   |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 18       | `height`        | Self-Reported Height (Meters)                   | numeric   |                                       | `R16HEIGHT`       |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 19       | `srh`           | Self-Reported Health Status                     | factor    | - Excellent                           | `R16SHLT`         |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - Very good                           |                   |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - Good                                |                   |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - Fair                                |                   |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - Poor                                |                   |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 20       | `act_vig`       | Vigorous Physical Activity Frequency            | factor    | - Every day                           | `R16VGACTX`       |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - \>1 per week                        |                   |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - 1 per week                          |                   |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - 1-3 per month                       |                   |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - Never                               |                   |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 21       | `bp`            | Ever Had High Blood Pressure                    | factor    | - No                                  | `R16HIBP`         |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - Yes                                 |                   |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 22       | `diab`          | Ever Had Diabetes                               | factor    | - No                                  | `R16DIABE`        |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - Yes                                 |                   |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 23       | `cancer`        | Ever Had Cancer                                 | factor    | - No                                  | `R16CANCRE`       |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - Yes                                 |                   |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 24       | `lung`          | Ever Had Lung Disease                           | factor    | - No                                  | `R16LUNGE`        |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - Yes                                 |                   |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 25       | `hrt`           | Ever Had Heart Problems                         | factor    | - No                                  | `R16HEARTE`       |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - Yes                                 |                   |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 26       | `strk`          | Ever Had Stroke                                 | factor    | - No                                  | `R16STROKE`       |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - Yes                                 |                   |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 27       | `psych`         | Ever Had Psychiatric Problems                   | factor    | - No                                  | `R16PSYCHE`       |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - Yes                                 |                   |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 28       | `sleep`         | Ever Had Sleep Disorder                         | factor    | - No                                  | `R16SLEEPE`       |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - Yes                                 |                   |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 29       | `arth`          | Ever Had Arthritis                              | factor    | - No                                  | `R16ARTHRE`       |
|          |                 |                                                 |           |                                       |                   |
|          |                 |                                                 |           | - Yes                                 |                   |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 30       | `cond_count`    | Total Number of Chronic Conditions              | numeric   | count (0-9)                           | `R16CONDE`        |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 31       | `cesd`          | CES-D Depression Score                          | numeric   | score (0-8)                           | `R16CESD`         |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+
| 32       | `income`        | Total Household Income                          | numeric   | dollars                               | `H16ITOT`         |
+----------+-----------------+-------------------------------------------------+-----------+---------------------------------------+-------------------+

: {.table-hover}
