---
title: "Workflow: Getting help"
author: "Nicky Wakim"
title-slide-attributes:
    data-background-color: "#3070BF"
format: 
  revealjs:
    theme: "../simple_NW.scss"
    chalkboard: true
    slide-number: true
    show-slide-number: all
    width: 1955
    height: 1100
    footer: "Workflow: Getting help"
    html-math-method: mathjax
    highlight-style: arrow
execute:
  echo: true
  freeze: auto
---

```{r}
#| label: "setup" 
#| include: false
#| message: false
#| warning: false

library(tidyverse)
library(lubridate)
library(janitor)
library(here)
```

# Learning Objectives

1. Learn to read some basic errors.
2. Searching R documentation
3. Searching forums
4. Using AI

# Getting help with R

## There are many ways to get help when you are stuck

1. [Use the `?` in front of the function name to get more information!]{style="color:#BF396F;"}
  
    -   Usually if I need help with the arguments for a function

2. [Google or go to stackoverflow.com]{style="color:#3070BF;"}
  
    - Often when I Google, I get redirected to something like stackoverflow
    - For example, let's say my `mean` function was outputting `NA`. I would Google something like "keep getting NA for mean in R" Then end up [here](https://stackoverflow.com/questions/25297705/mean-na-rm-true-still-returns-na)

3. [I can also go to my favorite AI tool to get help]{style="color:#459B99;"}
  
    - This is most useful for getting code started if it's complicated (we're not really at that level yet)
    - I asked ChatGPT "can you give me the code for calculating the mean in R"
        - [This is what I got](https://chatgpt.com/share/66f8a2b9-9918-8006-88af-0dc7b64bb86a)
    - For code generation, it gives you WAY too much
    - I also asked ChatGPT "Why is the mean function in R giving me an NA?" (in above link)
    
## More on AI usage

- [In the syllabus](https://nwakim.github.io/F24_EPI_525/syllabus.html#plagiarism-and-attribution)
- If you cannot trace code back to the class notes, then do NOT use it!
  - There's different coding practices and functions out there
  - I'm giving you a specific set of tools that will serve as a good introduction
  - You should be able to explain all your code and work 



